name: Publish
      
on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    tags:
      - "v*.*.*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Publish Windows
      run: dotnet publish ./sigparser-api/sigparser-api.csproj --self-contained true --output ./build-windows --runtime win-x64
    - name: Publish Linux
      run: dotnet publish ./sigparser-api/sigparser-api.csproj --self-contained true --output ./build-linux --runtime linux-x64
    - name: Zip Windows
      run: zip -r sigparser-api-win64.zip ./build-windows/*/
    - name: Zip Linux
      run: zip -r sigparser-api-linux.zip ./build-linux
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
            sigparser-api-win64.zip
            sigparser-api-linux.zip
